/* Inyecta paneles extra si faltan */
function injectExtraPanels(){
if(document.getElementById('panel-ip'))return;
var main=document.querySelector('main');if(!main)return;
var html=''
+'<section id="panel-ip" class="tool-panel"><div class="mb-2 text-xs text-sky-300/80 uppercase tracking-wider font-medium">Privacidad</div><h1 class="text-2xl font-bold text-white mb-2">IP y VPN</h1><p class="text-steel text-sm mb-4 max-w-2xl">IP publica, red y senales VPN. Requiere Internet (consulta desde tu navegador).</p><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><button id="ipBtn" onclick="runIpCheck()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Comprobar mi IP</button><div id="ipProgressWrap" class="hidden space-y-2"><div class="progress-track"><div id="ipProgress" class="progress-bar"></div></div><p id="ipStatus" class="text-sm text-neon"></p></div><div id="ipOut" class="text-sm"></div></div></section>'
+'<section id="panel-invisible" class="tool-panel"><div class="mb-2 text-xs text-emerald-300/80 uppercase tracking-wider font-medium">Seguridad</div><h1 class="text-2xl font-bold text-white mb-2">Caracteres invisibles</h1><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><div class="flex gap-2 flex-wrap"><button onclick="scanClipboardInvisible()" class="px-4 py-2.5 rounded-xl bg-neon text-void font-semibold text-sm">Leer portapapeles</button><button onclick="scanInvisibleInput()" class="px-4 py-2.5 rounded-xl border border-white/10 text-sm text-steel">Analizar cuadro</button></div><textarea id="invInput" class="w-full h-28 bg-void border border-white/10 rounded-xl px-4 py-3 text-sm text-white"></textarea><p id="invStatus" class="text-sm text-steel"></p><div id="invOut"></div></div></section>'
+'<section id="panel-homoglyphs" class="tool-panel"><div class="mb-2 text-xs text-emerald-300/80 uppercase tracking-wider font-medium">Seguridad</div><h1 class="text-2xl font-bold text-white mb-2">Dominios enganosos</h1><p class="text-steel text-sm mb-4 max-w-2xl leading-relaxed">Detecta letras de otros alfabetos que se ven como latinas. <strong class="text-mist">No significa que el dominio sea seguro</strong>: solo indica si se usaron (o no) esos trucos tipicos de phishing.</p><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><input id="homoInput" class="w-full bg-void border border-white/10 rounded-xl px-4 py-3 text-sm text-white" placeholder="ejemplo.com o https://..."><button onclick="checkHomoglyphs()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Analizar dominio</button><p id="homoStatus" class="text-sm text-steel"></p><div id="homoOut"></div></div></section>'
+'<section id="panel-qr" class="tool-panel"><div class="mb-2 text-xs text-cyan-300/80 uppercase tracking-wider font-medium">Enlaces</div><h1 class="text-2xl font-bold text-white mb-2">Generador QR</h1><p class="text-steel text-sm mb-4 max-w-2xl">Un solo enlace (http/https). Se genera en tu navegador; el PNG descargado es permanente.</p><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><input type="url" id="qrInput" class="w-full bg-void border border-white/10 rounded-xl px-4 py-3 text-sm text-white" placeholder="https://ejemplo.com/ruta" inputmode="url" autocomplete="off"><button onclick="generateQr()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Generar QR</button><p id="qrStatus" class="text-sm text-steel"></p><div id="qrCanvasWrap" class="flex justify-center py-2"></div><button id="qrDownload" class="hidden px-5 py-3 rounded-xl border border-neon/40 text-neon text-sm">Descargar PNG</button></div></section>'
+'<section id="panel-storage" class="tool-panel"><div class="mb-2 text-xs text-sky-300/80 uppercase tracking-wider font-medium">Privacidad</div><h1 class="text-2xl font-bold text-white mb-2">Almacenamiento local</h1><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><div class="flex flex-wrap gap-2"><button onclick="refreshStorageView()" class="px-4 py-2.5 rounded-xl bg-neon text-void font-semibold text-sm">Actualizar</button><button onclick="clearLocalStorageTool()" class="px-4 py-2.5 rounded-xl border border-red-500/30 text-red-300 text-sm">Vaciar localStorage</button><button onclick="clearSessionStorageTool()" class="px-4 py-2.5 rounded-xl border border-white/10 text-steel text-sm">Vaciar session</button></div><p id="storageStatus" class="text-sm text-steel"></p><div id="storageOut"></div></div></section>'
+'<section id="panel-permisos" class="tool-panel"><div class="mb-2 text-xs text-sky-300/80 uppercase tracking-wider font-medium">Privacidad</div><h1 class="text-2xl font-bold text-white mb-2">Permisos del navegador</h1><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><button onclick="checkPermissions()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Revisar permisos</button><div id="permProgressWrap" class="hidden space-y-2"><div class="progress-track"><div id="permProgress" class="progress-bar"></div></div><p id="permStatus" class="text-sm text-neon"></p></div><div id="permOut"></div></div></section>'
+'<section id="panel-filetype" class="tool-panel"><div class="mb-2 text-xs text-amber-300/80 uppercase tracking-wider font-medium">Archivos</div><h1 class="text-2xl font-bold text-white mb-2">Tipo real de archivo</h1><p class="text-steel text-sm mb-4 max-w-2xl">Lee los primeros bytes (magic bytes) y los compara con la extension del nombre. Todo local; el archivo no se sube.</p><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><input type="file" id="ftFile" class="block w-full text-sm text-steel file:mr-3 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-neon/15 file:text-neon"><button onclick="detectFileType()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Analizar</button><div id="ftOut" class="text-sm"></div></div></section>'
+'<section id="panel-blur" class="tool-panel"><div class="mb-2 text-xs text-amber-300/80 uppercase tracking-wider font-medium">Archivos</div><h1 class="text-2xl font-bold text-white mb-2">Desenfocar zonas</h1><p class="text-steel text-sm mb-4 max-w-2xl">Oculta caras, matriculas o datos sensibles antes de publicar. Arrastra rectangulos sobre la foto. Procesamiento local.</p><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-3xl space-y-4"><input type="file" id="blurFile" accept="image/*" class="block w-full text-sm text-steel file:mr-3 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-neon/15 file:text-neon"><div class="flex flex-wrap items-center gap-3"><label class="text-sm text-steel">Intensidad</label><input type="range" id="blurStrength" min="6" max="40" value="14" class="flex-1 max-w-xs"><span class="text-xs text-steel">pixelado</span></div><p id="blurStatus" class="text-sm text-steel">Elige una imagen</p><div class="overflow-auto max-h-[70vh] rounded-xl border border-white/10 bg-void"><canvas id="blurCanvas" class="max-w-full cursor-crosshair block mx-auto"></canvas></div><div id="blurActions" class="hidden flex flex-wrap gap-2"><button onclick="blurUndo()" class="px-4 py-2 rounded-xl border border-white/10 text-sm text-steel">Deshacer zona</button><button onclick="blurClear()" class="px-4 py-2 rounded-xl border border-white/10 text-sm text-steel">Limpiar zonas</button><button onclick="blurDownload()" class="px-5 py-2.5 rounded-xl bg-neon text-void font-semibold text-sm">Descargar PNG</button></div></div></section>';
var w=document.createElement('div');w.innerHTML=html;while(w.firstChild)main.appendChild(w.firstChild);
try{initBlurUI()}catch(e){}
}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',injectExtraPanels);}else{injectExtraPanels();}
