/* Inyecta paneles de herramientas nuevas si no están en el HTML */
document.addEventListener('DOMContentLoaded',()=>{
if(document.getElementById('panel-ip'))return;
const main=document.querySelector('main');if(!main)return;
const html=`
<section id="panel-ip" class="tool-panel"><div class="mb-2 text-xs text-cyan-300/80 uppercase tracking-wider font-medium">Red</div><h1 class="text-2xl sm:text-3xl font-bold text-white mb-2">IP y VPN</h1><p class="text-steel text-sm mb-4 max-w-2xl leading-relaxed">IP pública, red aproximada y señales de VPN/hosting. También sonda WebRTC. <strong class="text-mist">Requiere Internet</strong> (consulta desde tu navegador).</p><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><button id="ipBtn" onclick="runIpCheck()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Comprobar mi IP</button><div id="ipProgressWrap" class="hidden space-y-2"><div class="progress-track"><div id="ipProgress" class="progress-bar"></div></div><p id="ipStatus" class="text-sm text-neon"></p></div><div id="ipOut" class="text-sm"></div></div></section>
<section id="panel-invisible" class="tool-panel"><div class="mb-2 text-xs text-emerald-300/80 uppercase tracking-wider font-medium">Seguridad</div><h1 class="text-2xl sm:text-3xl font-bold text-white mb-2">Caracteres invisibles</h1><p class="text-steel text-sm mb-4 max-w-2xl">Detecta zero-width y marcas de dirección ocultas. Análisis 100% local.</p><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><div class="flex flex-wrap gap-2"><button onclick="scanClipboardInvisible()" class="px-4 py-2.5 rounded-xl bg-neon text-void font-semibold text-sm">Leer portapapeles</button><button onclick="scanInvisibleInput()" class="px-4 py-2.5 rounded-xl border border-white/10 text-sm text-steel">Analizar cuadro</button></div><textarea id="invInput" class="w-full h-28 bg-void border border-white/10 rounded-xl px-4 py-3 text-sm text-white" placeholder="O pega aquí el texto…"></textarea><p id="invStatus" class="text-sm text-steel"></p><div id="invOut"></div></div></section>
<section id="panel-qr" class="tool-panel"><div class="mb-2 text-xs text-cyan-300/80 uppercase tracking-wider font-medium">Red</div><h1 class="text-2xl sm:text-3xl font-bold text-white mb-2">Generador QR</h1><p class="text-steel text-sm mb-4 max-w-2xl">QR generado en el navegador. No se sube a ningún servicio.</p><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><textarea id="qrInput" class="w-full h-24 bg-void border border-white/10 rounded-xl px-4 py-3 text-sm text-white" placeholder="https://… o cualquier texto"></textarea><button onclick="generateQr()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Generar QR</button><p id="qrStatus" class="text-sm text-steel"></p><div id="qrCanvasWrap" class="flex justify-center py-2"></div><button id="qrDownload" class="hidden px-5 py-3 rounded-xl border border-neon/40 text-neon text-sm">Descargar PNG</button></div></section>
<section id="panel-storage" class="tool-panel"><div class="mb-2 text-xs text-violet-300/80 uppercase tracking-wider font-medium">Identidad</div><h1 class="text-2xl sm:text-3xl font-bold text-white mb-2">Almacenamiento local</h1><p class="text-steel text-sm mb-4 max-w-2xl">Solo datos de <strong class="text-mist">este origen</strong>. El navegador no permite ver otros sitios.</p><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><div class="flex flex-wrap gap-2"><button onclick="refreshStorageView()" class="px-4 py-2.5 rounded-xl bg-neon text-void font-semibold text-sm">Actualizar lista</button><button onclick="clearLocalStorageTool()" class="px-4 py-2.5 rounded-xl border border-red-500/30 text-red-300 text-sm">Vaciar localStorage</button><button onclick="clearSessionStorageTool()" class="px-4 py-2.5 rounded-xl border border-white/10 text-steel text-sm">Vaciar sessionStorage</button></div><p id="storageStatus" class="text-sm text-steel"></p><div id="storageOut" class="text-sm"></div></div></section>
<section id="panel-permisos" class="tool-panel"><div class="mb-2 text-xs text-violet-300/80 uppercase tracking-wider font-medium">Identidad</div><h1 class="text-2xl sm:text-3xl font-bold text-white mb-2">Permisos del navegador</h1><p class="text-steel text-sm mb-4 max-w-2xl">Estado de permisos para este origen. No activa cámara ni micrófono.</p><div class="p-6 rounded-2xl bg-panel border border-white/5 max-w-2xl space-y-4"><button onclick="checkPermissions()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Revisar permisos</button><div id="permProgressWrap" class="hidden space-y-2"><div class="progress-track"><div id="permProgress" class="progress-bar"></div></div><p id="permStatus" class="text-sm text-neon"></p></div><div id="permOut" class="text-sm"></div></div></section>`;
const w=document.createElement('div');w.innerHTML=html;while(w.firstChild)main.appendChild(w.firstChild);
});
