/* PDF tools adicionales (pdf-lib) */
async function pdfCreateBlank(){const n=Math.min(50,Math.max(1,+(document.getElementById('pdfCreateCount')?.value||1)));const out=document.getElementById('pdfCreateOut');if(out)out.textContent='Creando...';try{const doc=await PDFLib.PDFDocument.create();for(let i=0;i<n;i++)doc.addPage([595.28,841.89]);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([await doc.save()],{type:'application/pdf'}));a.download='vacio_'+n+'pag.pdf';a.click();if(out)out.textContent='Descargado'}catch(e){if(out)out.textContent='Error: '+e.message}}
async function pdfImagesToPdf(){const files=document.getElementById('pdfImgFiles')?.files;const out=document.getElementById('pdfImgOut');if(!files||!files.length){if(out)out.textContent='Elige imagenes';return}if(out)out.textContent='Convirtiendo...';try{const doc=await PDFLib.PDFDocument.create();for(const f of files){const bytes=await f.arrayBuffer();let img;if(/png/i.test(f.type)||/\.png$/i.test(f.name))img=await doc.embedPng(bytes);else img=await doc.embedJpg(bytes);const page=doc.addPage([img.width,img.height]);page.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([await doc.save()],{type:'application/pdf'}));a.download='imagenes.pdf';a.click();if(out)out.textContent='Descargado'}catch(e){if(out)out.textContent='Error (JPG/PNG): '+e.message}}
async function pdfExtractEach(){const f=document.getElementById('pdfEachFile')?.files?.[0];const out=document.getElementById('pdfEachOut');if(!f){if(out)out.textContent='Elige PDF';return}if(out)out.textContent='Extrayendo...';try{const src=await PDFLib.PDFDocument.load(await f.arrayBuffer());const n=src.getPageCount();for(let i=0;i<n;i++){const dest=await PDFLib.PDFDocument.create();const[p]=await dest.copyPages(src,[i]);dest.addPage(p);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([await dest.save()],{type:'application/pdf'}));a.download='pagina_'+(i+1)+'.pdf';a.click();await new Promise(r=>setTimeout(r,200))}if(out)out.textContent=n+' descargas'}catch(e){if(out)out.textContent='Error: '+e.message}}
async function pdfScale(){const f=document.getElementById('pdfScaleFile')?.files?.[0];const factor=+(document.getElementById('pdfScaleFactor')?.value||0.9);const out=document.getElementById('pdfScaleOut');if(!f){if(out)out.textContent='Elige PDF';return}if(out)out.textContent='Escalando...';try{const src=await PDFLib.PDFDocument.load(await f.arrayBuffer());const dest=await PDFLib.PDFDocument.create();const pages=await dest.copyPages(src,src.getPageIndices());pages.forEach(p=>{const{width,height}=p.getSize();p.setSize(width*factor,height*factor);p.scaleContent(factor,factor);dest.addPage(p)});const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([await dest.save()],{type:'application/pdf'}));a.download='escalado.pdf';a.click();if(out)out.textContent='Descargado'}catch(e){if(out)out.textContent='Error: '+e.message}}
async function pdfHeaderFooter(){const f=document.getElementById('pdfHeadFile')?.files?.[0];const head=(document.getElementById('pdfHeadText')?.value||'').trim();const foot=(document.getElementById('pdfFootText')?.value||'').trim();const out=document.getElementById('pdfHeadOut');if(!f){if(out)out.textContent='Elige PDF';return}if(out)out.textContent='Aplicando...';try{const doc=await PDFLib.PDFDocument.load(await f.arrayBuffer());const font=await doc.embedFont(PDFLib.StandardFonts.Helvetica);doc.getPages().forEach((page,i)=>{const{width,height}=page.getSize();if(head)page.drawText(head,{x:40,y:height-28,size:9,font,color:PDFLib.rgb(0.35,0.35,0.35)});if(foot){const t=foot.replace('{n}',String(i+1)).replace('{N}',String(doc.getPageCount()));page.drawText(t,{x:40,y:16,size:9,font,color:PDFLib.rgb(0.35,0.35,0.35)})}});const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([await doc.save()],{type:'application/pdf'}));a.download='cabecera_pie.pdf';a.click();if(out)out.textContent='Descargado'}catch(e){if(out)out.textContent='Error: '+e.message}}

(function injectPdfExtras(){
  if(document.getElementById('pdf-create'))return;
  var panel=document.getElementById('panel-pdf');
  if(!panel)return;
  var tabs=panel.querySelector('.flex.flex-wrap');
  if(tabs){
    var extras=[['each','Pag. sueltas'],['create','Crear vacio'],['img','Imagenes'],['scale','Escalar'],['head','Cabecera/pie']];
    extras.forEach(function(pair){
      if(tabs.querySelector('[data-pdf="'+pair[0]+'"]'))return;
      var b=document.createElement('button');
      b.className='pdf-tab px-3 py-1.5 rounded-xl border border-white/10 text-sm text-steel';
      b.setAttribute('data-pdf',pair[0]);
      b.textContent=pair[1];
      b.onclick=function(){showPdfSub(pair[0])};
      tabs.appendChild(b);
    });
  }
  var html=''
  +'<div id="pdf-each" class="pdf-sub p-6 rounded-2xl bg-panel border border-white/5 max-w-xl space-y-4"><p class="text-sm text-steel">Cada pagina como PDF aparte.</p><input type="file" id="pdfEachFile" accept="application/pdf" class="block w-full text-sm text-steel file:mr-3 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-neon/15 file:text-neon"><button onclick="pdfExtractEach()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Extraer todas</button><div id="pdfEachOut" class="text-sm text-steel"></div></div>'
  +'<div id="pdf-create" class="pdf-sub p-6 rounded-2xl bg-panel border border-white/5 max-w-xl space-y-4"><p class="text-sm text-steel">PDF en blanco A4.</p><input type="number" id="pdfCreateCount" min="1" max="50" value="1" class="w-full bg-void border border-white/10 rounded-xl px-4 py-3 text-sm text-white"><button onclick="pdfCreateBlank()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Crear</button><div id="pdfCreateOut" class="text-sm text-steel"></div></div>'
  +'<div id="pdf-img" class="pdf-sub p-6 rounded-2xl bg-panel border border-white/5 max-w-xl space-y-4"><p class="text-sm text-steel">JPG/PNG a PDF.</p><input type="file" id="pdfImgFiles" accept="image/jpeg,image/png" multiple class="block w-full text-sm text-steel file:mr-3 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-neon/15 file:text-neon"><button onclick="pdfImagesToPdf()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Convertir</button><div id="pdfImgOut" class="text-sm text-steel"></div></div>'
  +'<div id="pdf-scale" class="pdf-sub p-6 rounded-2xl bg-panel border border-white/5 max-w-xl space-y-4"><p class="text-sm text-steel">Escala 0.5-1.5.</p><input type="file" id="pdfScaleFile" accept="application/pdf" class="block w-full text-sm text-steel file:mr-3 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-neon/15 file:text-neon"><input type="number" id="pdfScaleFactor" min="0.5" max="1.5" step="0.05" value="0.9" class="w-full bg-void border border-white/10 rounded-xl px-4 py-3 text-sm text-white"><button onclick="pdfScale()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Escalar</button><div id="pdfScaleOut" class="text-sm text-steel"></div></div>'
  +'<div id="pdf-head" class="pdf-sub p-6 rounded-2xl bg-panel border border-white/5 max-w-xl space-y-4"><p class="text-sm text-steel">Cabecera/pie. Pie: {n}/{N}.</p><input type="file" id="pdfHeadFile" accept="application/pdf" class="block w-full text-sm text-steel file:mr-3 file:py-2 file:px-4 file:rounded-lg file:border-0 file:bg-neon/15 file:text-neon"><input type="text" id="pdfHeadText" class="w-full bg-void border border-white/10 rounded-xl px-4 py-3 text-sm text-white" placeholder="Cabecera"><input type="text" id="pdfFootText" class="w-full bg-void border border-white/10 rounded-xl px-4 py-3 text-sm text-white" value="Pag. {n} / {N}"><button onclick="pdfHeaderFooter()" class="px-5 py-3 rounded-xl bg-neon text-void font-semibold text-sm">Aplicar</button><div id="pdfHeadOut" class="text-sm text-steel"></div></div>';
  var w=document.createElement('div');w.innerHTML=html;while(w.firstChild)panel.appendChild(w.firstChild);
})();
